const airportCodes = {
  newYorkCity: ["LGA", "JFK"],
  chicago: ["MDW", "ORD"],
  charleston: ["LAS"],
  lasVegas: ["LAS"],
  seattle: ["SEA"],
  sanFrancisco: ["SFO"],
  washingtonDC: ["DCA"],
  newOrleans: ["MSY"],
  palmSprings: ["PSP"],
  sanDiego: ["SAN"],
  stLouis: ["STL"],
  sedona: ["SEZ", "SDX"],
  honolulu: ["HNL"],
  miami: ["MIA"],
  branson: ["BBG", "BKG"],
  boston: ["BOS"],
  orlando: ["MCO"],
  portland: ["PDX"],
  stAugustine: ["UST"],
  nashville: ["BNA"],
  losAngeles: ["LAX"],
  sanAntonio: ["SAT"],
  austin: ["AUS"],
  savannah: ["SAV"],
}